### ISSUE TITLE
Fanart broken?

### ISSUE THREAD

**Issue by jangrewe** [WarLion/skin.Aeon-Nox-4.1.9#3]
Hi, i just updated to the latest fernetmenta build of Gotham (which is tagged 14.0-ALPHA1) and fanart seems to be broken in your skin. It works fine in Aeon Nox 5.0.3.
I've explicitly enabled in (toggled through off, extra-fanart, fanart), but it doesn't show.
Let me know if you need any more infos, and thanks for keep AN4 alive!

**Comment by jhenkens** [comment]
Do you get the following in your log?

23:47:24 T:140130991978240 WARNING: Create - Unsupported protocol(image) in image://smb%3a%2f%2fDaenerys.lan%2fTV%2fGame%20of%20Thrones%2ffanart.jpg/

I use the theme with recent episodes background and widget, and the background doesn't seem to work until I mouse over the image in the widget, which causes the thumbnail to be cached. Once it is cached it seems to work fine.

**Comment by jangrewe** [comment]
I don't know what happened, but it seems to be working fine now. Maybe it was a problem with the xbmc build i was running... Either way: Thanks for your time! =)
