### ISSUE TITLE
Few issues on OpenElec

### ISSUE THREAD

**Issue by zorensen** [WarLion/skin.Aeon-Nox-4.1.9#7]
First of all, I love this skin. It looks amazing, and it's really the only skin I want ;)

However, I'm running into a few issues with it.

1) Every now and then I get this message;
"Alarm Clock - Cancelled with 0m10s left"
The amount of seconds varies. No idea why this message appears. Any idea on how I can get rid of this? Makes me crazy. Seems to appear often when I browsed through my movie or TV collection and are going back to the main menu.

2) I can't get text labels under my posters in the view showcase. Banners or logos works just fine ;) I found this error in my logfile though; "ERROR: unmatched parentheses in Skin.HasSetting(NoFloorLabelTVshows". That might have something to do with it?

Please advise if anyone can help me out with this.

**Comment by WarLion** [comment]
thanks zorensen
I will look into that 
about the missing ) do you remember in wich file the log said the)  is missing?

**Comment by WarLion** [comment]
also I forget do you use a custom keymap?
edit: never mind i just find it you are right i actually miss 2 ")"  i will fix it soon

**Comment by zorensen** [comment]
Wow! Quick answer and great work, WarLion.
What you do with this skin is awesome! I simply love it :-)

Are the two missing ) the reason I cant have textlabels under my movie/tv posters? Please let me know which files that needs to be updated, so I can solve this on my setup.

Again; Thanks a million for the help and this awesome skin!

**Comment by zorensen** [comment]
Never mind, just saw you've made the changes :-) Thanks! I'll let you know how it turns out :-)

**Comment by WarLion** [comment]
the text label was a bug that I already fix I don't think the missing )  was causing any problem but is better to had all the code fix lol
about you alarm clock the only thing I can think is a custom keymap that's is causing a trouble there but not sure, if you can share a log I can see if something is causing you that problem
